version: '3.4'

services:
  apipractice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
       - ./server:/app
       - /app/obj/
       - /app/bin/
       - /app/out/